{"title":"swagger的一次报错","slug":"swagger的一次报错","date":"2020-02-05T07:23:55.123Z","updated":"2020-02-09T15:32:07.297Z","comments":true,"path":"api/articles/swagger的一次报错.json","excerpt":" [Figure] ","covers":["https://picabstract-preview-ftn.weiyun.com/ftn_pic_abs_v3/69620481005299099481eb81c5f2e50eb194113e4a2299f9dc52c7b74a8b90922681eb80760177dfd16cc2e8b11d5375?pictype=scale&amp;from=30113&amp;version=3.3.3.3&amp;uin=1643994375&amp;fname=swagger2.png&amp;size=750"],"content":"<p><img src=\"https://picabstract-preview-ftn.weiyun.com/ftn_pic_abs_v3/69620481005299099481eb81c5f2e50eb194113e4a2299f9dc52c7b74a8b90922681eb80760177dfd16cc2e8b11d5375?pictype=scale&amp;from=30113&amp;version=3.3.3.3&amp;uin=1643994375&amp;fname=swagger2.png&amp;size=750\" alt><a id=\"more\"></a></p>\n<h2 id=\"报错Unable-to-infer-base-url\"><a href=\"#报错Unable-to-infer-base-url\" class=\"headerlink\" title=\"报错Unable to infer base url.\"></a>报错Unable to infer base url.</h2><p>最近在搭脚手架 加入swagger2的时候 run项目发现突然报错了，错误信息如下<br><figure class=\"highlight plain\"><table><tr><td class=\"gutter\"><pre><span class=\"line\">1</span><br><span class=\"line\">2</span><br><span class=\"line\">3</span><br><span class=\"line\">4</span><br></pre></td><td class=\"code\"><pre><span class=\"line\">Unable to infer base url.</span><br><span class=\"line\">This is common when using dynamic servlet registration or when the API is behind an API Gateway.</span><br><span class=\"line\">The base url is the root of where all the swagger resources are served. For e.g. if the api is available at http://example.org/api/v2/api-docs then the base url is http://example.org/api/.</span><br><span class=\"line\">Please enter the location manually:</span><br></pre></td></tr></table></figure></p>\n<h2 id=\"问题排查\"><a href=\"#问题排查\" class=\"headerlink\" title=\"问题排查\"></a>问题排查</h2><p>第一反应是启动类未定义相应注解，看了之后排除了，之后就考虑到了版本问题，最开始引入的是2.8版本，感觉不太顺手，又回退版本到2.4，这成为了本次问题的关键，将浏览器的缓存清除后，问题完美解决</p>\n<h2 id=\"end\"><a href=\"#end\" class=\"headerlink\" title=\"end\"></a>end</h2>","more":"</p>\n<h2 id=\"报错Unable-to-infer-base-url\"><a href=\"#报错Unable-to-infer-base-url\" class=\"headerlink\" title=\"报错Unable to infer base url.\"></a>报错Unable to infer base url.</h2><p>最近在搭脚手架 加入swagger2的时候 run项目发现突然报错了，错误信息如下<br><figure class=\"highlight plain\"><table><tr><td class=\"gutter\"><pre><span class=\"line\">1</span><br><span class=\"line\">2</span><br><span class=\"line\">3</span><br><span class=\"line\">4</span><br></pre></td><td class=\"code\"><pre><span class=\"line\">Unable to infer base url.</span><br><span class=\"line\">This is common when using dynamic servlet registration or when the API is behind an API Gateway.</span><br><span class=\"line\">The base url is the root of where all the swagger resources are served. For e.g. if the api is available at http://example.org/api/v2/api-docs then the base url is http://example.org/api/.</span><br><span class=\"line\">Please enter the location manually:</span><br></pre></td></tr></table></figure></p>\n<h2 id=\"问题排查\"><a href=\"#问题排查\" class=\"headerlink\" title=\"问题排查\"></a>问题排查</h2><p>第一反应是启动类未定义相应注解，看了之后排除了，之后就考虑到了版本问题，最开始引入的是2.8版本，感觉不太顺手，又回退版本到2.4，这成为了本次问题的关键，将浏览器的缓存清除后，问题完美解决</p>\n<h2 id=\"end\"><a href=\"#end\" class=\"headerlink\" title=\"end\"></a>end</h2>","categories":[{"name":"swagger","path":"api/categories/swagger.json"}],"tags":[{"name":"swagger","path":"api/tags/swagger.json"}]}